### ISSUE TITLE
Connecting mod with other liquid sources

### ISSUE THREAD

**Issue by RastaTux** [minetest-mods/pipeworks#155]
Hello there!
I am building my first mod for minetest and my first idea was, to make filthy/polluted water. It will be created by for example the homedecor toilet or sink, or nearby technic mod coal oven. It makes gras dirt to dry gras dirt and living corals to coral skeletons. Many other implementations are imaginable.

But my most interesting point was to connect it to pipeworks. I have my own "pump" block, that is activated by punching the homedecor toilet. Now i want, that this pump is connected with pipeworks and the spigot should spit out filthy/polluted water. I already implemented big parts of the mod, including a filth water loaded pipe_3.

But i have problems in connecting my pump and my polluted water filled pipes with the rest of the pipeworks pipes (i wanted to use your empty pipes as basic system. I would need your help in how i could get the pipe connections, can somebody from you help me? I think, it would be way easier if the branch [new_flow_logic](https://github.com/minetest-mods/pipeworks/commits/new_flow_logic) is ready. I would help, but it's a bit too complicated for me right now. :( You'll find my mod over here: [getting_hands_dirty/develop](https://github.com/RastaTux/getting_hands_dirty/tree/develop).

Greetings,
RastaTux

**Comment by VanessaE** [comment]
This is the plan one day, and I had planned to use `new_flow_logic` as the foundation, but that branch never got the attention it deserved, and anyway it's unusable now.  Maybe some day.

**Comment by thetaepsilon-gamedev** [comment]
It should be noted that I'm currently doing work on replacement flowing logic for the pipes, so it's likely that any code trying to interface with the "classic mode" is likely not going to work with it.
On that ground, I would suggest that this particular issue is closed.
That said, the new mechanism is now a reincarnation of the deprecated new_flow_logic and more besides, and it is already technically possible to register a pump device to work with the new pressure logic from another mod, but right now all pipes can only carry water.

Carrying other fluids (or non-fluids... VanessaE has mentioned other mods could use steam, for instance) is not currently possible, as it would either require a complete separate set of nodes that don't interact for each registered liquid/substance/whatever type, or be necessary to deal with mixed fluids in pipes (what happens if lava and water meet in a pipe? how does a spigot pour out such a mixture? etc.)

Given the age of this issue and of the linked repository, I would still recommend closing this issue, however as support for other pipe substances could be seen as desirable I will endeavour to make a record of interest in this feature.
