### ISSUE TITLE
Teleport tubes are not always working

### ISSUE THREAD

**Issue by ForbiddenJ** [minetest-mods/pipeworks#166]
I'm experiencing problems with the teleport tubes even though 2 are connected to the same channel.

![screenshot from 2017-04-01 17-30-22](https://cloud.githubusercontent.com/assets/26123860/24582971/d421f4fa-1701-11e7-87b2-87dfef6cfb2b.png)

I placed the left tube and then the right tube, and then configured them with the same channel in that order. The second sends its items as expected. However, the first one fails.
Don't mind the weird connections. The tubes always send their received items into their connected chests due to their injectors not taking them.

This private server is running the release version of minetest 0.4.15 along with these mods/modpacks

minetest-mod-mesecons, digilines, minetest-3d_armor, technic, moreores, pipeworks, cme, hud_hunger, areas, railcorridors, showbones, stained_glass, charcoal, craft_lookup

Where [stained_glass](https://github.com/ForbiddenJ/stained_glass), [meseport](https://github.com/ForbiddenJ/meseport), [charcoal](https://github.com/ForbiddenJ/charcoal), and craft_lookup (in development) are my own mods and [showbones](https://github.com/ForbiddenJ/showbones) is my fork.

**Comment by Ekdohibs** [comment]
If one fails and not the other, the probable cause is that only one is configured for receiving, could you check that please?

**Comment by ForbiddenJ** [comment]
They both have their receive switches on, and yet they are still giving me issues.

**Comment by HybridDog** [comment]
l tested a bit and noticed that the teleport tube doesn't insert the item to the tube correctly after receiving it:
![screenshot_20170409_130631](https://cloud.githubusercontent.com/assets/3192173/24836789/a2059574-1d25-11e7-8bce-8bf29b855507.png)

**Comment by VanessaE** [comment]
Is this still an issue?

**Comment by ForbiddenJ** [comment]
I'm gonna have a look again on the same private server that I had issues on.

@HybridDog, Maybe you need to use regular tubes. I noticed just now that you used crossing tubes.

**Comment by DS-Minetest** [comment]
Some weeks or months ago the teleport tubes didn't work for me but now they do.

**Comment by ForbiddenJ** [comment]
Yes. I'm still having an issue with teleport tubes.

**Comment by HybridDog** [comment]
Yes, maybe that was the problem.

**Comment by thetaepsilon-gamedev** [comment]
More recently, I have come across this problem on the LS-Survival server where teleport tubes were completely inoperable.
It turns out that string.format("%d", hash) was clamping every value to 2^31-1, causing a hash collision which overwrote the table entry.
I will be following up with a patch to warn about hash collisions; in the meantime, [this commit](https://github.com/minetest-mods/pipeworks/commit/57fc8c67f827a41ab1278fd0d25b2566032da61a) fixes the issue in a backwards-compatible manner by using %.30g, which should always precisely print the value even on 32-bit systems, as it avoids the round trip as a C int in the underlying use of sprintf().

@ForbiddenJ testing for this would be appreciated if it is still affecting you.
If this works, I will be closing this issue and https://github.com/minetest-mods/pipeworks/pull/192 also.

**Comment by HybridDog** [comment]
I think you can use "%ld" for long int. ($ man 3 printf)

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
