### ISSUE TITLE
Add a tube for alternating exits

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/pipeworks#170]
A tube could have one entrance and two exits, the items alternately leave the left and right exit.
In the marble machine it's shown how it works:
https://www.youtube.com/watch?v=IvUU8joBb1Q
1:31 look on the right, the marbles there are alternately falling left and right
3:18 a star can be used for decoration

**Comment by VanessaE** [comment]
Tubes already do that if you put Pipeworks in "cyclic" mode, which is the default setting.

**Comment by HybridDog** [comment]
Sorry, l need to correct myself. In pipeworks such a tube has two entrances.
So you can use it e.g. to ensure that items have enough distance to each other:
![screenshot_20170410_120926](https://cloud.githubusercontent.com/assets/3192173/24857365/481cb998-1de8-11e7-8998-d59e38bd27c1.png)
It may even be possible to make semaphores.

**Comment by VanessaE** [comment]
Try using a sorting tube with no items in its formspec - just turn the rows "off" that items should never exit through.

**Comment by HybridDog** [comment]
> Try using a sorting tube with no items in its formspec - just turn the rows "off" that items should never exit through.

l don't understand how you can use the sorting tube to ensure that items have enough distance to each other.

**Comment by DS-Minetest** [comment]
Idk how your construction should always make the same distance.

So, I built the construction with the addition of a filter and a chest and digiline chest with a lcd and a luacontroller with
```
if event.type == "program" then
 mem.otime = os.clock()
elseif event.type == "digiline" and event.channel == "chest" then
 local ntime = os.clock()
 digiline_send("lcd", ntime-mem.otime)
 mem.otime = ntime
end
```
to calculate time:
![screenshot_20170410_182737](https://cloud.githubusercontent.com/assets/7613443/24872821/feb56976-1e1e-11e7-9797-ff74c1568b59.png)
But I'm still confused what the meaning of this issue is.

**Comment by HybridDog** [comment]
This video (those 10 secons) fits better: https://www.youtube.com/watch?v=1GbMYvYZEHc&t=69
It's called [marble flip flop](http://www.sentex.net/~mwandel/marbles/flipflop.html) mechanism.
![http://www.sentex.net/~mwandel/marbles/flipflop.html](http://www.sentex.net/~mwandel/marbles/flip.png)
In pipeworks the item can't just come from above but also from one of the two sides.

**Comment by DS-Minetest** [comment]
In pipeworks in tubes in meta is an int saved (called tubedir I think). Every time an item passes the tube, the int is counted one up (if the limit(depending on how many connections the tube has) is reached, it's set back to 1), the item goes in the direction told by the int. So, there's one number that is affected by all directions and effects all directions.

**Comment by asl97** [comment]
@HybridDog I don't think we get the issue here,  what would be the use case of maintaining the same distance?

(Afaik) Normal tube already cycle between output.  one can use a sorting tube to block outputting to specific tube.

If you mean the bug where item end up going in circle even when there is an empty chest like the setup in your screenshot,  that's probably an bug.

https://youtu.be/n4nP6XTj3Qg

**Comment by VanessaE** [comment]
@HybridDog  if you use a sorting tube with the input side set to "off" and only two outputs connected, you'll get exactly the behavior you ask for in that marble flip-flop.  For example:
![image](https://cloud.githubusercontent.com/assets/1733537/24936955/3ce59018-1efb-11e7-9983-fa9e6d05fe5f.png)
The blue side of this sorting tube is turned "off", all others are turned "on" and there are no items in any slots.  Since I use "cyclic" mode in Pipeworks, items arriving at the blue input are routed alternately to the white and black outputs.  You could do the same with just about any other tube, but at least with a sorting tube, you can ensure items never go back out through the input side.

**Comment by HybridDog** [comment]
You can't do this with sorting tubes:
![screenshot_20170412_163129](https://cloud.githubusercontent.com/assets/3192173/24963206/3b6a36b4-1f9e-11e7-9be9-dae45b96ecea.png)

**Comment by DS-Minetest** [comment]
Hm, we could add a programmable tube, crafted with luacontroller and sorting pipe and behaves like both two mixed.

**Comment by benrob0329** [comment]
+1 to a flip flop tube.

**Comment by asl97** [comment]
@HybridDog What your image seem to suggest is it going in a figure eight (or a ∞ if you prefer) which is already working as shown in this video.

https://youtu.be/oi8k1QsYLeU

**Comment by HybridDog** [comment]
@asl97 No, while the first flipflip is toggled, the pending item need to wait until it's toggled again.
And l showed only an example usage.

**Comment by asl97** [comment]
Ain't that more like a lock?   How does the "marble flip flop" fit into it?

Are you asking for a tube which blocks item from entering the last entrance?
The blocked entrance would get unblock when another item entered from another entrance and that entrance get blocked?

If anything,  it seem like **the end result of**\* what you are asking for can be made using a chest and filter which is something I call a buffer.  as for the toggle, something like a detector tube should work.

\* since it would get toggle when one item pass through, only one item can pass through per toggle

https://youtu.be/_lvWV7lZDSw
Note how the gold block goes into the loop then the diamond block.  pending item are in the chest

**Comment by asl97** [comment]
addition note to be added to last post:
you can use two 'key' item to make sure it's never empty so it doesn't stop working, a sorting tube to always send the key back into the (chest) and let the rest of the stuff through another tube.

**Comment by HybridDog** [comment]
Thanks, l didn't know there were so many possibilities available due to cyclic mode.
Anyway, the flipflop tube may be a simple tube fitting well for special purposes.
And it can be decorative.

**Comment by VanessaE** [comment]
Ok so a sorting tube has one weakness when used the way you want.  If you really need to precisely replicate the behavior of a marble flip-flop, and have some space around the junction to spare, use an ordinary tube as the junction, and one-way tubes on all three inputs - one pointing toward it, the others pointing away.

If space is a problem, then the best option is not to add a special tube, but to let a sorting tube refuse to take incoming items from a particular direction, with toggle-switches to control the feature, to complement the existing refuse-outgoing option.  Then you could flick the "allow-outgoing" switch to "off" for your input side, and the "allow-incoming" switches to "off" for the output sides.

I'm not inclined to accept a pull request for another tube type, but I'd be happy with the above modification to the sorting tube.

**Comment by electrodude** [comment]
To space items out evenly, can't you just have a digiline detector tube going into a chest, and connect the digiline detector tube to a luacontroller which tells a digiline filter-injector to pull things from the chest at appropriately timed intervals?  Using tubes as a holding area seems like a bad idea to me, especially with the introduction of the broken pipe.
