### ISSUE TITLE
Food inside node breaker

### ISSUE THREAD

**Issue by LemonFox3008** [minetest-mods/pipeworks#211]
I accidently left some food in a node breaker on a server and when it activated via blinky plant the server crashed.
I have no access to the error logs but i guess it was because the food was attempted to be "used" and was "eaten" by the machine which could not support it.
This is a MAJOR problem as a troublemaker could destroy a server with just a nodebreaker an apple and a blinky plant

**Comment by Ekdohibs** [comment]
Could you give us some information on which mods are enabled on that server please?

**Comment by LemonFox3008** [comment]
I do not run the server but i know it has mods including:
Pipeworks
The more food mod (i cant remeber the name)
mesecons
usual

I am 95% sure it was due to pipeworks however
Try reproducing the error by placing a nodebreaker with a blinky plant next to it and then placing an item of food in the machine

**Comment by Ekdohibs** [comment]
It is due to a bad interaction between pipeworks and the food mod the server is using. Depending on the code of the food mod, the fix has to be either in pipeworks or in that mod -- thus, I can't do anything until I know which mod it is precisely; and even then; the fix might need to be in that mod.

**Comment by LemonFox3008** [comment]
The fix should be in pipeworks.
Pipeworks is the one that is placing the effect on the server.
Also there are many food mods - and one pipeworks 
Can this be set to a higher priority?

**Comment by raymoo** [comment]
It's probably due to the use of a hacky player object. It has caused crashes with other items too, such as Stu's guns (maybe this one has been fixed).

I would say that it isn't really a bug if the food mod expected a real player, as the API promises. However, it could probably add hacky compatibility code to handle hacky fake player tables.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
