### ISSUE TITLE
Have filters move the biggest stack they can first.

### ISSUE THREAD

**Issue by KristopherKram** [minetest-mods/pipeworks#56]
I created an auto-sorting system using pipeworks and the system works but the quarries that fill the system have filters next to them and the filters always grab the new stack of cobble which only holds about 1-5 cobble so the chest slowly fills up because it is constantly grabbing the small stack of cobble when in should instead grab my large stack of 32 diamonds.

In short filters should grab the biggest stack they can so they are not inefficiently grabbing small stacks instead of moving large stacks.

**Comment by yo-we** [comment]
Furthermore, the consequence of this would be that the items taken from a chest will not be taken in the order they have been placed by a user, too.

**Comment by electrodude** [comment]
This problem seems to have be fixed long ago, although in a different way, by `Sequence slots by Rotation` mode, which was added in b832c0ad.  Put a Stackwise Filter-Injector in rotation mode, and it will take slot 1, then slot 2, the slot 3, and so on, while the chest still gets filled from the front.
