### ISSUE TITLE
Detector tubes output too short of a pulse to be useful

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/pipeworks#67]
The detector tubes seem to output such a short pulse that most things will not pick it up, and in some cases they don't even emit a pulse at all.

**Comment by yo-we** [comment]
The issue is still present today. Can it be fixed?

**Comment by yorik** [comment]
It's still happens from time to time. Looks like nobody cares:(

**Comment by VanessaE** [comment]
I'm sure people care, but it's an intermittent issue that affects only a few people.

Seems to me that increasing this calculated step value would fix the issue:

https://github.com/minetest-mods/pipeworks/blob/master/signal_tubes.lua#L2

Maybe make it 5* instead of 2*.  That would make the pulse last about half a second at the usual 0.1s server step interval.

**Comment by HybridDog** [comment]
l assume the "pulse"s can interact with each other because of the usage of minetest.after.

**Comment by yorik** [comment]
I tried to tweak dedicated_server_step but luacontroller is still missing some of items passing through tube.

**Comment by HybridDog** [comment]
yorik, you could use minetest.chat_send_all to tell when an item enters the tube,
if it tells you every item entering the tube but the mesecons signal doesn't work every time, the mesecons signal may be sent delayed in a queue and it gets disabled before the queue becomes updated,
so before the signal is passed to the wires and luacontroller, it's disabled, so it doesn't arrive at the luacontroller,
a digiline detector tube could work better.

**Comment by VanessaE** [comment]
1bfc2d4e5b19b643190c4996b458eb3d63f8152c
